<?php

/**
 * @file
 * Contains hook implementations for svg_upload_sanitizer module.
 */

use Drupal\file\FileInterface;
use Drupal\svg_upload_sanitizer\HookHandler\FileInsertHookHandler;

/**
 * Implements hook_entity_type_insert().
 */
function svg_upload_sanitizer_file_insert(FileInterface $file) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(FileInsertHookHandler::class)
    ->process($file);
}
