name: paragon
recipe: drupal10
config:
  webroot: docroot
  database: mysql:5.7
  php: '8.1'
services:
  appserver:
    xdebug: true
  solr:
    type: solr:7
    core: collection1
    portforward: true
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
