name: Build and Deploy to Remote
run-name: Build and Deploy to Remote
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy_to_remote:
    uses: elevatedthird/actions/.github/workflows/build_deploy.yml@main
    secrets: inherit
    with:
      DESTINATION_REPOSITORY: ${{ vars.DESTINATION_REPOSITORY }}
      NODE_VERSION: '18'
      PHP_VERSION: '8.1'
      THEME_NAME: 'kinetic'
      PLATFORM: 'acquia'
