name: Build and Deploy to Remote
run-name: Build and Deploy to Remote
on:
  push:
    tags:
      - '*'
    branches:
      - master
      - develop
      - main
      - md-*
  workflow_dispatch:
jobs:
  build_and_deploy_to_remote:
    uses: elevatedthird/actions/.github/workflows/build_deploy.yml@main
    secrets: inherit
