name: Build and Deploy to Remote
run-name: Build and Deploy to Remote
on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - master
      - main
      - md-*
  workflow_dispatch:
jobs:
  build_and_deploy_to_remote:
    uses: elevatedthird/actions/.github/workflows/build_deploy.yml@main
    secrets: inherit
