<?php

/**
 * @file
 * This is a Drupal 10 settings.ddev.php file automatically generated by DDEV.
 *
 * DDEV manages this file and may delete or overwrite it unless this
 * comment, marked with #ddev-generated, is removed. It is recommended
 * that you leave this file alone.
 */

$host = "db";
$port = 3306;
$driver = "mysql";

$databases['default']['default']['database'] = "db";
$databases['default']['default']['username'] = "db";
$databases['default']['default']['password'] = "db";
$databases['default']['default']['host'] = $host;
$databases['default']['default']['port'] = $port;
$databases['default']['default']['driver'] = $driver;

// Set $settings['config_sync_directory'] if not set in settings.php.
if (empty($settings['config_sync_directory'])) {
  $settings['config_sync_directory'] = 'sites/default/files/sync';
}

/**
 * Local file directory configuration
 */
$settings['file_public_path'] = 'sites/default/files';
$settings['file_private_path'] = 'sites/default/files/private';
$settings['file_temp_path'] = 'sites/default/files/private/tmp';

$settings['vite'] = [
  'devServerUrl' => 'https://' . $_ENV['DDEV_HOSTNAME'] . ':5173',
  'baseUrl' => '/themes/custom/kinetic/dist/',
  'devDependencies' => [
    'kinetic/vite-client'
  ],
];

/**
 * Add DDEV to trusted host patterns.
 */
$settings['trusted_host_patterns'] = ['.*'];

